package servlets;

import java.io.IOException;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.Cookie;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import datastructures.*;

/**
 * Servlet implementation class Login
 */
@WebServlet("/Login")
public class Login extends HttpServlet {
	private static final long serialVersionUID = 1L;
	public String loginMessage = "";
       
    /**
     * @see HttpServlet#HttpServlet()
     */
    public Login() {
        super();
        // TODO Auto-generated constructor stub
    }

	/**
	 * @see HttpServlet#doGet(HttpServletRequest request, HttpServletResponse response)
	 */
	protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		//User user = (User) request.getSession().getAttribute("user");
		DatabaseConnection dbc = (DatabaseConnection) request.getSession().getAttribute("dbc");
		if(dbc == null) {
			String dbURL = "jdbc:derby://localhost:1527/UNSWDatabase;create=true;user=user;password=user";
			dbc = new DatabaseConnection(dbURL);
			dbc.createConnection();
			request.getSession().setAttribute("dbc", dbc);
		}
		request.setAttribute("loginMessage", this.loginMessage);
		request.setAttribute("registrationMessage", "");
//		request.setAttribute("username", "");
//		request.setAttribute("email", "");
//		request.setAttribute("firstname", "");
//		request.setAttribute("surname", "");
		this.loginMessage = "";
		request.getRequestDispatcher("login.jsp").forward(request, response);
	}

	/**
	 * @see HttpServlet#doPost(HttpServletRequest request, HttpServletResponse response)
	 */
	protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		String user = request.getParameter("username");
		String pwd  = request.getParameter("password");
		
		if (user == null || pwd == null || user.equals("") || pwd.equals("")) {
			this.loginMessage = "Please enter your username and password";
			doGet(request, response);
		}else{
			UserDAO usd = new UserDAOImpl();
			Integer id = usd.validate(user, pwd);
			if (id == null){
				this.loginMessage = "Invalid username or password";
				doGet(request, response);
			}else{
				this.loginMessage = "";
				HttpSession login = request.getSession(true);
				login.setAttribute("user", id); // FIXME: Change to user id generated by database once we pick a schema
				Integer expiry = 15 * 60; 
				login.setMaxInactiveInterval(expiry);
				response.sendRedirect("Home");
			}
		}
	}

}