drop table UNSWBOOKUSER;
drop table UNSWBOOKPOST;

create table UNSWBOOKUSER(
  ID integer NOT NULL UNIQUE GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  USERNAME varchar(30) UNIQUE,
  PWD varchar(30),
  NAME varchar(30),
  EMAIL varchar(30) UNIQUE);
  
create table UNSWBOOKPOST(
  ID integer NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  USERID integer references UNSWBOOKUSER(id),
  POST varchar(30),
  POSTED timestamp
  );